//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTestGit
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDAT
    {
        public int matricule { get; set; }
        public string nom { get; set; }
        public string prénom { get; set; }
        public string mail { get; set; }
        public int telephone { get; set; }
        public string niveau { get; set; }
        public int experience { get; set; }
        public string dernier_employeur { get; set; }
        public string cv_employeur { get; set; }
    }
}
